# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crejprob <- function(pe, ps, x1, n1, n2, zalpha) {
    .Call('STARTdesign_crejprob', PACKAGE = 'STARTdesign', pe, ps, x1, n1, n2, zalpha)
}

rejprob <- function(pe, ps, r1, n1, n2, zalpha) {
    .Call('STARTdesign_rejprob', PACKAGE = 'STARTdesign', pe, ps, r1, n1, n2, zalpha)
}

